[package]
name = "mdlink"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
arboard = { version = "3.2.1", default-features = false }
clap = { version = "4.4.6", features = ["derive"] }
env_logger = "0.10.0"
format = "0.2.4"
itertools = "0.11.0"
joinery = "3.1.0"
log = "0.4.20"
regex = "1.10.2"
url = "2.4.1"
